/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#004ccd",
        "primary-container": "#0f62fe",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#f3f3ff",
        "on-primary-fixed": "#00174c",
        "on-primary-fixed-variant": "#003da9",
        "inverse-primary": "#b4c5ff",

        "secondary": "#5e5e5e",
        "secondary-container": "#e1dfdf",
        "secondary-fixed": "#e4e2e2",
        "secondary-fixed-dim": "#c7c6c6",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#626263",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary-fixed-variant": "#464747",

        "tertiary": "#9e3100",
        "tertiary-container": "#c84000",
        "tertiary-fixed": "#ffdbd0",
        "tertiary-fixed-dim": "#ffb59d",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fff1ed",
        "on-tertiary-fixed": "#390c00",
        "on-tertiary-fixed-variant": "#832700",

        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",

        "surface": "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-variant": "#e2e2e2",
        "surface-operator": "#f2f4f8",
        "surface-tint": "#0052dd",

        "on-surface": "#1a1c1c",
        "on-surface-variant": "#424656",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
        "background": "#f9f9f9",
        "on-background": "#1a1c1c",

        "outline": "#737687",
        "outline-variant": "#c3c6d8",
        "border-subtle": "#e0e0e0",

        "critical-red": "#da1e28",
        "high-warning-orange": "#ff832b",
        "medium-caution-yellow": "#f1c21b",
        "success-green": "#24a148",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.25rem",
        "md": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "2xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "base": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "gutter": "16px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        sans: ["IBM Plex Sans", "sans-serif"],
        "headline-md": ["IBM Plex Sans", "sans-serif"],
        "headline-lg": ["IBM Plex Sans", "sans-serif"],
        "headline-xl": ["IBM Plex Sans", "sans-serif"],
        "headline-lg-mobile": ["IBM Plex Sans", "sans-serif"],
        "body-lg": ["IBM Plex Sans", "sans-serif"],
        "body-md": ["IBM Plex Sans", "sans-serif"],
        "label-md": ["IBM Plex Sans", "sans-serif"],
        "label-sm": ["IBM Plex Sans", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      boxShadow: {
        "ai-glow": "0 0 40px -10px rgba(15, 98, 254, 0.35)",
        "card": "0 2px 6px rgba(0,0,0,0.06)",
        "card-hover": "0 8px 24px rgba(0,0,0,0.08)",
        "modal": "0 16px 48px -12px rgba(0, 0, 0, 0.18)",
      }
    },
  },
  plugins: [],
}
